version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  docker-build:
      environment:
        IMAGE_NAME: danshoff/bookstore-api-node
      docker:
        - image: circleci/buildpack-deps:strech
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker image
            command: docker build -t $IMAGE_NAME:latest
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - docker-build:
            filters:
              branches:
                only: master